---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: tokoro-os
description: Tokoro OS — JDM-themed, adaptive gaming distro

base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: signing
